### PR TITLE
If the target database is not created yet, pg-nano dev should create it.

### PR DESCRIPTION
**Pull request by sedationh**
https://github.com/pg-nano/pg-nano/issues/31

### CODE REVIEW

**Comment by aleclarson** [comment]
Nice! Let's move that logic to https://github.com/pg-nano/pg-nano/blob/cd9581f11c23bd4bafaa5f99446e9429350c681c/src/cli/env.ts#L108-L119, so it's not used in production. This way, an error will be reported if trying to connect to a non-existent database in production, which I believe is the ideal behavior.

**Comment by sedationh** [comment]
```
repos/test-pg-nano - (main) > /Users/seda/workspace/repos/pg-nano/dist/pg-nano/cli/main.js dev
[23:39] • Loading config file ./pg-nano.config.ts
[23:39] • add sql/post.pgsql
[23:39] • Connecting to database postgres://seda@localhost:5432/2?application_name=pg-nano
[23:39] • create database:  2
```

```
postgres-# \l
                                         List of databases
   Name    | Owner | Encoding | Collate | Ctype | ICU Locale | Locale Provider | Access privileges 
-----------+-------+----------+---------+-------+------------+-----------------+-------------------
 2         | seda  | UTF8     | C       | C     |            | libc            | 
 mydb      | seda  | UTF8     | C       | C     |            | libc            | 
 postgres  | seda  | UTF8     | C       | C     |            | libc            | 
 template0 | seda  | UTF8     | C       | C     |            | libc            | =c/seda          +
           |       |          |         |       |            |                 | seda=CTc/seda
 template1 | seda  | UTF8     | C       | C     |            | libc            | =c/seda          +
           |       |          |         |       |            |                 | seda=CTc/seda
```

**Comment by sedationh** [comment]
Got it. You want to distinguish between dev and production behavior for connecting to non-existent databases. I'll think about designing the code tomorrow ~

**Comment by sedationh** [comment]
Normal situation

```
repos/test-pg-nano - (main) > /Users/seda/workspace/repos/pg-nano/dist/cli/main.js dev
[21:06] • Loading config file ./pg-nano.config.ts
[21:06] • add sql/post.pgsql
[21:06] • Connecting to database postgres://seda@localhost:5432/5?application_name=pg-nano
[21:06] • DATABASE: 5 CREATED
```

The condition in which the connect fails
use `connectionString: "postgres://seda@localhost:432/5",`
```
[21:22] • Loading config file ./pg-nano.config.ts
[21:22] • add sql/post.pgsql
[21:22] • Connecting to database postgres://seda@localhost:432/5?application_name=pg-nano
[21:22] ⚠️ Error: connection to server at "localhost" (127.0.0.1), port 432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 432 failed: Connection refused
        Is the server running on that host and accepting TCP/IP connections?
```

**Comment by sedationh** [comment]
I don't see a way to differentiate between Dev and production yet.So I just add the logic at where you say

**Comment by aleclarson** [comment]
Thanks for getting this in 🎉

**Pull request merged**
